//! Compiles the built-in templates and static assets into the binary.
//!
//! `embed_templates!` also validates template syntax at build time — an
//! invalid built-in template fails the build, not the first request
//! (`00` §8.5). Static assets embed the same way, so the `/static` handler
//! serves from the binary, never the filesystem (`00` §8.6).

use std::fs;
use std::path::{Path, PathBuf};

/// Templates live at the repo root beside the static assets, outside the
/// crate, so every web-facing artifact sits under `web/`.
const WEB_TEMPLATES: &str = "../../web/templates";
/// Static assets: css, vendored js (`00` §8.6).
const WEB_STATIC: &str = "../../web/static";

fn main() {
    minijinja_embed::embed_templates!(WEB_TEMPLATES, &[".j2"]);
    embed_static_assets();
}

/// Generates `static_files.rs` in `OUT_DIR`: a `static ASSETS:
/// &[(&str, &[u8])]` table mapping asset names (`css/app.css`) to their
/// bytes. Names are forward-slash relative to `web/static`, sorted for a
/// deterministic build.
fn embed_static_assets() {
    // Canonicalize: `include_bytes!` paths resolve relative to the
    // generated file (in OUT_DIR), so the emitted paths must be absolute.
    let root = Path::new(WEB_STATIC)
        .canonicalize()
        .expect("web/static must exist for the build");
    println!("cargo:rerun-if-changed={WEB_STATIC}");
    let mut names: Vec<String> = Vec::new();
    collect(&root, &root, &mut names);
    names.sort();
    let mut code = String::new();

    code.push_str("// @generated by build.rs — do not edit.\n");
    code.push_str("pub static ASSETS: &[(&str, &[u8])] = &[\n");
    for name in &names {
        let abs = root.join(name);
        code.push_str(&format!(
            "    ({name:?}, include_bytes!({abs:?})),\n",
            abs = abs.display().to_string(),
        ));
    }
    code.push_str("];\n");
    let out_dir = std::env::var_os("OUT_DIR").expect("cargo sets OUT_DIR for build scripts");
    let dst = PathBuf::from(out_dir).join("static_files.rs");
    fs::write(&dst, code).expect("write static_files.rs");
}

/// Recursively collect file names relative to `root`, skipping dotfiles
/// (same rule as `minijinja_embed`).
fn collect(root: &Path, dir: &Path, out: &mut Vec<String>) {
    let entries = match fs::read_dir(dir) {
        Ok(entries) => entries,
        Err(_) => return,
    };
    for entry in entries.flatten() {
        let name = entry.file_name();
        if name.to_string_lossy().starts_with('.') {
            continue;
        }
        let path = entry.path();
        if path.is_dir() {
            collect(root, &path, out);
        } else if let Ok(rel) = path.strip_prefix(root) {
            out.push(rel.to_string_lossy().replace('\\', "/"));
        }
    }
}
